#!/usr/bin/env bash
# Displays username, other user data and home the home directory from /etc/passwd

while IFS=: read -r user pass uid gid info home shell
do
  echo "$user - $home - $shell"
done < /etc/passwd
